In [1]:
import sys
from collections import defaultdict
import csv
from datetime import datetime, time, timedelta
from math import floor, lcm
from causis_api.const import login
login.username = "jinqiao.xue"
login.password = "1101BX@causis"
from causis_api.const import *
from causis_api.data import *

获取每日可交易期权合约并提取相关信息

In [4]:
date_str = "2020-11-10"
opt_chain = all_instruments('O', date_str)
opt_chain = opt_chain[opt_chain["Code"] == "159915"]
opt_chain["expire"] = [datetime.strptime(i, "%Y-%m-%d") for i in opt_chain["EndDate"]]
tmp = instruments(opt_chain["Symbol"])[["OptType", "StrikePrice",'MinTick','Multiplier']]
opt_chain["OptType"] = tmp["OptType"].tolist()
opt_chain["Strike"] = tmp["StrikePrice"].tolist()
opt_chain["MinTick"] = tmp["MinTick"].tolist()
opt_chain["Multiplier"] = tmp["Multiplier"].tolist()
opt_chain[['Symbol','Name','BeginDate','EndDate','OptType','Strike',"MinTick","Multiplier"]]
opt_chain

KeyError: "None of [Index(['OptType', 'StrikePrice', 'MinTick', 'Multiplier'], dtype='object')] are in the [columns]"

获取指定日期分钟级别指定期权合约数据

In [25]:
df = get_price(["O.CN.SZSE.159915.90006532","O.CN.SZSE.159915.90006533",'O.CN.SZSE.159915.90006534','O.CN.SZSE.159915.90006536'],start_date = "2025-01-01",end_date = "2025-12-23",frequency= "minute1")
df=df[['SYMBOL','CLOCK','OPEN','HIGH','LOW','CLOSE','VOLUME']]
df=df[df['SYMBOL']=="O.CN.SZSE.159915.90006532"]
df['DATE']=pd.to_datetime(df['CLOCK']).dt.date
df = df[df['DATE']==pd.to_datetime("2025-12-23").date()]
df

,SYMBOL,CLOCK,OPEN,HIGH,LOW,CLOSE,VOLUME,DATE
9360,O.CN.SZSE.159915.90006532,2025-12-23 09:31:00,0.5301,0.5301,0.5301,0.5301,0.0,2025-12-23
9361,O.CN.SZSE.159915.90006532,2025-12-23 09:32:00,0.5301,0.5301,0.5301,0.5301,0.0,2025-12-23
9362,O.CN.SZSE.159915.90006532,2025-12-23 09:33:00,0.5301,0.5301,0.5301,0.5301,0.0,2025-12-23
9363,O.CN.SZSE.159915.90006532,2025-12-23 09:34:00,0.5301,0.5301,0.5301,0.5301,0.0,2025-12-23
9364,O.CN.SZSE.159915.90006532,2025-12-23 09:35:00,0.5301,0.5301,0.5301,0.5301,0.0,2025-12-23
...,...,...,...,...,...,...,...,...
9595,O.CN.SZSE.159915.90006532,2025-12-23 14:56:00,0.5231,0.5231,0.5231,0.5231,0.0,2025-12-23
9596,O.CN.SZSE.159915.90006532,2025-12-23 14:57:00,0.5231,0.5231,0.5231,0.5231,0.0,2025-12-23
9597,O.CN.SZSE.159915.90006532,2025-12-23 14:58:00,0.5231,0.5231,0.5231,0.5231,0.0,2025-12-23
9598,O.CN.SZSE.159915.90006532,2025-12-23 14:59:00,0.5231,0.5231,0.5231,0.5231,0.0,2025-12-23
9599,O.CN.SZSE.159915.90006532,2025-12-23 15:00:00,0.5231,0.5231,0.5231,0.5231,0.0,2025-12-23

获取ETF分钟级别数据

In [3]:
df = get_price("S.CN.SZSE.159915",start_date = "2020-01-01",end_date = "2021-01-01",frequency= "minute1")
df[['SYMBOL','CLOCK','OPEN','HIGH','LOW','CLOSE','VOLUME']]

,SYMBOL,CLOCK,OPEN,HIGH,LOW,CLOSE,VOLUME
0,S.CN.SZSE.159915,2020-01-02 09:31:00,1.743,1.744,1.741,1.742,10930300.0
1,S.CN.SZSE.159915,2020-01-02 09:32:00,1.741,1.742,1.737,1.737,1380400.0
2,S.CN.SZSE.159915,2020-01-02 09:33:00,1.737,1.738,1.735,1.736,1800300.0
3,S.CN.SZSE.159915,2020-01-02 09:34:00,1.736,1.737,1.736,1.737,4554600.0
4,S.CN.SZSE.159915,2020-01-02 09:35:00,1.737,1.737,1.734,1.734,3523100.0
...,...,...,...,...,...,...,...
58315,S.CN.SZSE.159915,2020-12-31 14:56:00,2.865,2.866,2.863,2.866,2768500.0
58316,S.CN.SZSE.159915,2020-12-31 14:57:00,2.865,2.866,2.864,2.865,2436300.0
58317,S.CN.SZSE.159915,2020-12-31 14:58:00,2.865,2.865,2.865,2.865,23900.0
58318,S.CN.SZSE.159915,2020-12-31 14:59:00,2.865,2.865,2.865,2.865,0.0
58319,S.CN.SZSE.159915,2020-12-31 15:00:00,2.865,2.866,2.865,2.866,4364000.0

In [6]:
df = get_price("O.CN.SZSE.159915.90006532",start_date = "2020-01-01",end_date = "2026-01-01",frequency= "day")
df[['SYMBOL','CLOCK','OPEN','HIGH','LOW','CLOSE','VOLUME']]

,SYMBOL,CLOCK,OPEN,HIGH,LOW,CLOSE,VOLUME
0,O.CN.SZSE.159915.90006532,2025-10-29,0.4703,0.4703,0.4703,0.4703,1.0
1,O.CN.SZSE.159915.90006532,2025-10-30,0.4739,0.5270,0.4739,0.5160,704.0
2,O.CN.SZSE.159915.90006532,2025-10-31,0.5163,0.5719,0.5050,0.5690,486.0
3,O.CN.SZSE.159915.90006532,2025-11-03,0.6074,0.6137,0.5790,0.5790,52.0
4,O.CN.SZSE.159915.90006532,2025-11-04,0.6220,0.6400,0.6220,0.6400,9.0
5,O.CN.SZSE.159915.90006532,2025-11-05,0.6516,0.6685,0.5990,0.6012,103.0
6,O.CN.SZSE.159915.90006532,2025-11-06,0.5800,0.5800,0.5399,0.5399,18.0
7,O.CN.SZSE.159915.90006532,2025-11-07,0.5707,0.5707,0.5326,0.5326,33.0
8,O.CN.SZSE.159915.90006532,2025-11-10,0.5300,0.6064,0.5300,0.5850,34.0
9,O.CN.SZSE.159915.90006532,2025-11-11,0.5536,0.6228,0.5518,0.6208,322.0
10,O.CN.SZSE.159915.90006532,2025-11-12,0.6507,0.6675,0.6163,0.6178,410.0
11,O.CN.SZSE.159915.90006532,2025-11-13,0.6291,0.6291,0.5540,0.5770,17.0
12,O.CN.SZSE.159915.90006532,2025-11-14,0.5789,0.6120,0.5789,0.6120,6.0
13,O.CN.SZSE.159915.90006532,2025-11-17,0.6430,0.6430,0.6312,0.6312,3.0
14,O.CN.SZSE.159915.90006532,2025-11-18,0.6300,0.6778,0.6300,0.6682,15.0
15,O.CN.SZSE.159915.90006532,2025-11-19,0.6426,0.6685,0.6340,0.6685,16.0
16,O.CN.SZSE.159915.90006532,2025-11-20,0.6361,0.6960,0.6361,0.6954,26.0
17,O.CN.SZSE.159915.90006532,2025-11-21,0.7284,0.8055,0.7284,0.8052,150.0
18,O.CN.SZSE.159915.90006532,2025-11-24,0.7975,0.8280,0.7742,0.8088,73.0
19,O.CN.SZSE.159915.90006532,2025-11-25,0.7695,0.7695,0.6998,0.7531,373.0
20,O.CN.SZSE.159915.90006532,2025-11-26,0.7531,0.7531,0.6689,0.7051,248.0
21,O.CN.SZSE.159915.90006532,2025-11-27,0.6800,0.7222,0.6321,0.7222,102.0
22,O.CN.SZSE.159915.90006532,2025-11-28,0.7230,0.7230,0.6764,0.6950,58.0
23,O.CN.SZSE.159915.90006532,2025-12-01,0.6860,0.6901,0.6550,0.6550,73.0
24,O.CN.SZSE.159915.90006532,2025-12-02,0.6600,0.6822,0.6600,0.6732,95.0
25,O.CN.SZSE.159915.90006532,2025-12-03,0.6482,0.7047,0.6451,0.6949,58.0
26,O.CN.SZSE.159915.90006532,2025-12-04,0.6830,0.7086,0.6601,0.6636,96.0
27,O.CN.SZSE.159915.90006532,2025-12-05,0.6500,0.6698,0.6121,0.6176,385.0
28,O.CN.SZSE.159915.90006532,2025-12-08,0.5926,0.5926,0.5213,0.5449,300.0
29,O.CN.SZSE.159915.90006532,2025-12-09,0.5473,0.5473,0.4974,0.5248,146.0
30,O.CN.SZSE.159915.90006532,2025-12-10,0.5462,0.5820,0.5232,0.5291,305.0
31,O.CN.SZSE.159915.90006532,2025-12-11,0.4986,0.5687,0.4862,0.5687,403.0
32,O.CN.SZSE.159915.90006532,2025-12-12,0.5581,0.5742,0.5271,0.5383,184.0
33,O.CN.SZSE.159915.90006532,2025-12-15,0.5615,0.5768,0.5532,0.5768,28.0
34,O.CN.SZSE.159915.90006532,2025-12-16,0.6216,0.6481,0.6199,0.6347,316.0
35,O.CN.SZSE.159915.90006532,2025-12-17,0.6387,0.6409,0.5588,0.5588,94.0
36,O.CN.SZSE.159915.90006532,2025-12-18,0.5707,0.6019,0.5707,0.5865,13.0
37,O.CN.SZSE.159915.90006532,2025-12-19,0.5951,0.5953,0.5802,0.5948,10.0
38,O.CN.SZSE.159915.90006532,2025-12-22,0.5490,0.5490,0.5301,0.5301,18.0
39,O.CN.SZSE.159915.90006532,2025-12-23,0.5185,0.5244,0.5001,0.5233,70.0
40,O.CN.SZSE.159915.90006532,2025-12-24,0.5089,0.5185,0.4844,0.4911,91.0

下一个交易日

In [24]:
date = "2025-12-20"
result = get_next_trading_date(date, 1)
result

'2025-12-22'

获取起点和终点之间的交易日

In [25]:
result = get_trading_dates("2025-07-10", "2025-07-20")
print(result)

['2025-07-10', '2025-07-11', '2025-07-14', '2025-07-15', '2025-07-16', '2025-07-17', '2025-07-18']